#!/usr/bin/env python3
"""gatehouse reconciler: decide which sites are reachable from the internet.

Traefik has two HTTPS entrypoints:
  websecure      :443   LAN and VPN clients. Every router lives here.
  websecure-ext  :9443  The only port the public tunnel forwards to.

A site is public if and only if it has a router on websecure-ext. This script
reads every router from the other files in Traefik's dynamic directory, and
for each hostname marked PUBLIC in the state file it writes a copy of that
router onto websecure-ext into one generated file, gatehouse.yml. Private
sites simply have no copy, so :9443 answers 404 for them while :443 keeps
serving them on the LAN.

The file is written atomically (temp file + rename) and only when its
content changes, so Traefik's file watcher does not churn. It is safe to run
from a timer and from the CLI at the same time.

Settings come from the environment:
  GATEHOUSE_DYNAMIC_DIR   Traefik dynamic config dir (default /srv/traefik/dynamic)
  GATEHOUSE_STATE         desired-state JSON file   (default /srv/gatehouse/state.json)
  GATEHOUSE_EXT_ENTRYPOINT                          (default websecure-ext)
  GATEHOUSE_DESIRED_URL   optional HTTP endpoint returning {"public": [hosts]};
                          if set and reachable it wins over the state file.

Usage: reconcile.py [--dry-run]
"""
import json
import os
import re
import sys
import tempfile
import urllib.request

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required (apt install python3-yaml)")

OUT_NAME = "gatehouse.yml"
HEADER = ("# Generated by gatehouse. Do not edit by hand.\n"
          "# A hostname is reachable from the internet only if it has a router here.\n")
_HOST = re.compile(r"Host\(`([^`]+)`\)")


def settings():
    return {
        "dyn": os.environ.get("GATEHOUSE_DYNAMIC_DIR", "/srv/traefik/dynamic"),
        "state": os.environ.get("GATEHOUSE_STATE", "/srv/gatehouse/state.json"),
        "ep": os.environ.get("GATEHOUSE_EXT_ENTRYPOINT", "websecure-ext"),
        "url": os.environ.get("GATEHOUSE_DESIRED_URL", ""),
    }


def hosts_of(rule):
    return set(_HOST.findall(rule or ""))


def load_source_routers(dyn):
    """Every router in dynamic/*.yml except our own output and backup copies."""
    routers = {}
    for fn in sorted(os.listdir(dyn)):
        if not fn.endswith((".yml", ".yaml")) or fn == OUT_NAME or ".bak" in fn:
            continue
        try:
            with open(os.path.join(dyn, fn)) as f:
                doc = yaml.safe_load(f) or {}
        except (OSError, yaml.YAMLError) as e:
            print(f"WARN: skipping {fn}: {e}", file=sys.stderr)
            continue
        for name, r in ((doc.get("http") or {}).get("routers") or {}).items():
            routers[name] = r
    return routers


def desired_public(cfg):
    """-> (set of public hostnames, where the answer came from)."""
    if cfg["url"]:
        try:
            with urllib.request.urlopen(cfg["url"], timeout=4) as resp:
                return set(json.load(resp).get("public", [])), "url"
        except (OSError, ValueError):
            pass  # fall back to the local file
    try:
        with open(cfg["state"]) as f:
            d = json.load(f)
        return {h for h, s in d.get("hosts", {}).items() if s.get("state") == "PUBLIC"}, "file"
    except (OSError, ValueError) as e:
        print(f"WARN: no desired state ({e}); treating every host as private", file=sys.stderr)
        return set(), "empty"


def build(routers, public, ep):
    out = {}
    for name, r in routers.items():
        if not (hosts_of(r.get("rule")) & public):
            continue
        ext = {"entryPoints": [ep], "rule": r["rule"], "service": r["service"], "tls": r.get("tls") or {}}
        if r.get("priority") is not None:
            ext["priority"] = r["priority"]
        if r.get("middlewares"):
            ext["middlewares"] = list(r["middlewares"])
        out[f"{name}-ext"] = ext
    return {"http": {"routers": dict(sorted(out.items()))}}


def render(doc):
    return HEADER + yaml.safe_dump(doc, sort_keys=True, default_flow_style=False)


def reconcile(cfg=None, dry_run=False):
    cfg = cfg or settings()
    public, src = desired_public(cfg)
    doc = build(load_source_routers(cfg["dyn"]), public, cfg["ep"])
    new = render(doc)
    out = os.path.join(cfg["dyn"], OUT_NAME)
    old = open(out).read() if os.path.exists(out) else ""
    n = len(doc["http"]["routers"])
    if new == old:
        return f"unchanged: {n} ext routers for {len(public)} public hosts (state from {src})"
    if dry_run:
        return f"would write {out}: {n} ext routers for {len(public)} public hosts (state from {src})\n{new}"
    fd, tmp = tempfile.mkstemp(dir=cfg["dyn"], prefix=".gatehouse.", suffix=".tmp")
    with os.fdopen(fd, "w") as f:
        f.write(new)
    # mkstemp creates the file 0600. Anything else that reads Traefik's config
    # (a monitor generator, a backup) then silently fails, so make it 0644.
    os.chmod(tmp, 0o644)
    os.replace(tmp, out)
    return f"wrote {out}: {n} ext routers for {len(public)} public hosts (state from {src})"


if __name__ == "__main__":
    print(reconcile(dry_run="--dry-run" in sys.argv[1:]))
